# Form implementation generated from reading ui file 'entryWidget.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(771, 300)
        self.Window = QtWidgets.QLineEdit(parent=Form)
        self.Window.setGeometry(QtCore.QRect(40, 20, 641, 261))
        self.Window.setStyleSheet("border-color: rgb(0, 0, 0);")
        self.Window.setObjectName("Window")
        self.UploadS = QtWidgets.QPushButton(parent=Form)
        self.UploadS.setGeometry(QtCore.QRect(60, 240, 161, 24))
        self.UploadS.setStyleSheet("border-color: rgb(0, 0, 0);\n"
"selection-color: rgb(104, 104, 104);\n"
"background-color: rgb(182, 182, 182);")
        self.UploadS.setObjectName("UploadS")
        self.UploadLabel = QtWidgets.QLabel(parent=Form)
        self.UploadLabel.setGeometry(QtCore.QRect(60, 80, 171, 16))
        self.UploadLabel.setObjectName("UploadLabel")
        self.ChooseFile = QtWidgets.QPushButton(parent=Form)
        self.ChooseFile.setGeometry(QtCore.QRect(60, 100, 61, 16))
        self.ChooseFile.setStyleSheet("border-color: rgb(0, 0, 0);\n"
"font: 300 7pt \"Segoe UI\";\n"
"selection-color: rgb(104, 104, 104);\n"
"background-color: rgb(182, 182, 182);")
        self.ChooseFile.setObjectName("ChooseFile")
        self.SequenceNameLabel = QtWidgets.QLabel(parent=Form)
        self.SequenceNameLabel.setGeometry(QtCore.QRect(60, 190, 241, 16))
        self.SequenceNameLabel.setObjectName("SequenceNameLabel")
        self.SequenceTypeLabel = QtWidgets.QLabel(parent=Form)
        self.SequenceTypeLabel.setGeometry(QtCore.QRect(60, 140, 91, 16))
        self.SequenceTypeLabel.setObjectName("SequenceTypeLabel")
        self.TypeMenu = QtWidgets.QComboBox(parent=Form)
        self.TypeMenu.setGeometry(QtCore.QRect(160, 140, 81, 22))
        self.TypeMenu.setStyleSheet("font: 7pt \"Segoe UI\";")
        self.TypeMenu.setObjectName("TypeMenu")
        self.TypeMenu.addItem("")
        self.TypeMenu.addItem("")
        self.TypeMenu.addItem("")
        self.TypeMenu.addItem("")
        self.TypeMenu.addItem("")
        
        self.sequenceEntryInput = QtWidgets.QLineEdit(parent=Form)
        self.sequenceEntryInput.setGeometry(QtCore.QRect(60, 50, 451, 21))
        self.sequenceEntryInput.setStyleSheet("border-color: rgb(0, 0, 0);")
        self.sequenceEntryInput.setClearButtonEnabled(False)
        self.sequenceEntryInput.setObjectName("sequenceEntryInput")

        self.nameEntry = QtWidgets.QLineEdit(parent=Form)
        self.nameEntry.setGeometry(QtCore.QRect(60, 210, 451, 21))
        self.nameEntry.setObjectName("nameEntry")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.UploadS.setText(_translate("Form", "Upload Sequences"))
        self.UploadLabel.setText(_translate("Form", "or upload a file"))
        self.ChooseFile.setText(_translate("Form", "Choose File"))
        self.SequenceNameLabel.setText(_translate("Form", "Give your sequence a name (optional)"))
        self.SequenceTypeLabel.setText(_translate("Form", "Sequence Type"))
        self.TypeMenu.setItemText(0, _translate("Form", "FASTA (DNA)"))
        self.TypeMenu.setItemText(1, _translate("Form", "FASTA (Protein)"))
        self.TypeMenu.setItemText(2, _translate("Form", "EMBL"))
        self.TypeMenu.setItemText(3, _translate("Form", "GCC"))
        self.TypeMenu.setItemText(4, _translate("Form", "Genbank"))
        self.sequenceEntryInput.setText(_translate("Form", "Enter sequence here..."))
        self.nameEntry.setText(_translate("Form", "Enter name here..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
